---

- name: "Install Lua 5.4"
  apt:
    name: lua5.4
    state: present
    install_recommends: no
- name: "Use Lua 5.4 by default"
  command: update-alternatives --set lua-interpreter /usr/bin/lua5.4
- name: "Add Prosody package signing key"
  apt_key:
    url: "https://packages.prosody.im/debian/pubkey.asc"
- name: "Add Prosody package repo"
  apt_repository:
    filename: prosody
    repo: "deb https://packages.prosody.im/debian bookworm/snapshots/{{ prosody.snapshot }} main"
- name: "Install Prosody package"
  apt:
    name: "{{ prosody.package }}"
    state: present
    install_recommends: no
- name: "Deploy Prosody config"
  copy:
    src: ../files/prosody.cfg.lua
    dest: /etc/prosody/prosody.cfg.lua
- name: "Create Prosody data directory"
  file:
    state: directory
    path: /snikket/prosody
    owner: prosody
    group: prosody
    mode: 0750
- name: "Create Prosody modules directory"
  file:
    state: directory
    path: /etc/prosody/modules
- name: "Create Prosody firewall directory"
  file:
    state: directory
    path: /etc/prosody/firewall
- name: "Create web root directory"
  file:
    state: directory
    path: /var/www
- name: "FIXME Workaround for Prosody package bug"
  file:
    path: /etc/prosody/certs
    state: directory
    owner: prosody
    group: adm
    mode: 0750
    recurse: yes
- name: "Delete localhost cert created by package postinst script"
  file:
    path: "/etc/prosody/certs/{{ item }}"
    state: absent
  loop:
    - localhost.crt
    - localhost.key
- name: "Disable Prosody init script"
  service:
    name: prosody
    enabled: no
    use: sysvinit
- name: "Stop Prosody if running"
  service:
    name: prosody
    state: stopped
    use: sysvinit
- name: "Allow Prosody to bind service ports"
  command: setcap 'cap_net_bind_service=+ep' /usr/bin/lua5.4

- name: "Create Prosody modules source directory"
  file:
    state: directory
    path: /usr/local/lib/prosody-modules

- name: Download prosody-modules
  unarchive:
    src: "https://hg.prosody.im/prosody-modules/archive/{{ prosody_modules.revision }}.tar.gz"
    remote_src: true
    extra_opts: "--strip-components=1"
    dest: /usr/local/lib/prosody-modules
- name: Enable wanted modules (prosody-modules)
  file:
    state: link
    src: "/usr/local/lib/prosody-modules/{{item}}"
    dest: "/etc/prosody/modules/{{item}}"
  loop:
    - mod_cloud_notify
    - mod_cloud_notify_extensions
    - mod_cloud_notify_encrypted
    - mod_cloud_notify_priority_tag
    - mod_cloud_notify_filters
    - mod_block_registrations
    - mod_conversejs
    - mod_migrate_http_upload
    - mod_lastlog2
    - mod_limit_auth
    - mod_password_policy
    - mod_vcard_muc
    - mod_email
    - mod_http_altconnect
    - mod_firewall
    - mod_admin_notify
    - mod_http_oauth2
    - mod_http_admin_api
    - mod_rest
    - mod_groups_migration
    - mod_invites_api
    - mod_invites_groups
    - mod_invites_page
    - mod_invites_register_api
    - mod_invites_tracking
    - mod_groups_internal
    - mod_groups_muc_bookmarks
    - mod_muc_defaults
    - mod_muc_local_only
    - mod_muc_offline_delivery
    - mod_http_host_status_check
    - mod_measure_process
    - mod_spam_reporting
    - mod_watch_spam_reports
    - mod_isolate_host
    - mod_muc_auto_reserve_nicks
    - mod_measure_active_users
    - mod_measure_lua
    - mod_measure_malloc
    - mod_http_xep227
    - mod_portcheck
    - mod_sasl2
    - mod_sasl2_bind2
    - mod_sasl2_sm
    - mod_sasl2_fast
    - mod_client_management
    - mod_audit
    - mod_audit_auth
    - mod_audit_status
    - mod_audit_user_accounts
    - mod_password_policy
    - mod_s2s_status
    - mod_sasl_ssdp
    - mod_privilege
    - mod_admin_blocklist
    - mod_muc_moderation
    - mod_push2

- name: Enable wanted modules (snikket-modules)
  file:
    state: link
    src: "/usr/local/lib/snikket-modules/{{item}}"
    dest: "/etc/prosody/modules/{{item}}"
  loop:
    - mod_update_check
    - mod_update_notify
    - mod_invites_default_group
    - mod_invites_bootstrap
    - mod_snikket_client_id
    - mod_snikket_ios_preserve_push
    - mod_snikket_restricted_users
    - mod_snikket_deprecate_general_muc
    - mod_migrate_snikket_roles
    - mod_health_report
    - mod_snikket_server_vcard
    - mod_snikket_billing
    - mod_snikket_version

- name: "Install mod_firewall rules"
  copy:
    src: ../files/restricted_users.pfw
    dest: /etc/prosody/firewall/
    mode: 0644

- name: "Install lua-ossl for encrypted push notifications"
  apt:
    name: lua-luaossl
    state: present
    install_recommends: no

- name: "Install luaunbound"
  apt:
    name: lua-unbound
    state: present
    install_recommends: no

- name: "Install lua-readline"
  apt:
    name: lua-readline
    state: present
    install_recommends: no

- name: "Install DNS root data (for DNSSEC keys)"
  apt:
    name: dns-root-data
    state: present
    install_recommends: no

- name: "Install Prosody-Migrator"
  apt:
    name: prosody-migrator-trunk
    state: present
    install_recommends: no
- name: "Copy Prosody-Migrator config"
  copy:
    src: ../files/migrator.cfg.lua
    dest: /etc/prosody/migrator.cfg.lua
- name: "Install LuaDBI driver for SQLite3"
  apt:
    name: lua-dbi-sqlite3
    state: present
    install_recommends: no

- name: "Apply Prosody module patches"
  patch:
    src: "{{item}}"
    basedir: "/usr/lib/prosody/modules"
    strip: 1
  with_fileglob:
    - "../files/patches/prosody/modules/*.patch"

- name: Create Snikket resources directory
  file:
    state: directory
    path: /usr/local/share/snikket
    owner: root
    group: root
    mode: 0755

- name: Install Snikket logo
  copy:
    src: ../files/snikket-logo.png
    dest: /usr/local/share/snikket/logo.png
    owner: root
    group: root
    mode: 0644
