---
name: Docker release image build

"on":
  push:
    tags:
      - release/*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: >-
          echo "Building ref $GITHUB_REF...";
          RELEASE_TAG="${GITHUB_REF#refs/tags/release/}";
          RELEASE_SERIES="${RELEASE_TAG%.*}" ;
          RELEASE_VER="${RELEASE_TAG#$RELEASE_SERIES.}";
          docker build . \
            --file docker/Dockerfile \
            --build-arg=BUILD_SERIES="$RELEASE_SERIES" \
            --build-arg=BUILD_ID="$RELEASE_VER" \
            --tag snikket/snikket:"$RELEASE_SERIES"
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u snikket --password-stdin
      - name: Push the Docker image
        run: docker push snikket/snikket:dev
